version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'
        volumes:
            - ./app/back-end:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        volumes:
           - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        env_file:
            - app/back-end/var/.env
    
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1 

    